services:
  db:
    image: postgres:16
    container_name: blog_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      target: web
    container_name: blog_web
    working_dir: /app/app
    command: gunicorn --config gunicorn.conf.py app.wsgi:application
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app

  test:
    build:
      context: .
      target: test
    command: test-blog
    profiles:
      - test
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
