# Generated by Django 6.0.2 on 2026-03-07 00:00

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_image"),
    ]

    operations = [
        TrigramExtension(),
    ]
